[tool.poetry]
name = "homework-osnovi-git"
version = "0.1.0"
description = ""
authors = ["yuliya valeeva <jul.valeewa@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
